sonar.projectKey=cohort-9-mern-6825-syeda
sonar.projectName=Cohort-9 MERN Note Taking App
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/Note-Taking-App/src,backend
sonar.tests=frontend/Note-Taking-App/src/tests,backend/tests

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/*.config.js,frontend/Note-Taking-App/src/tests/**,backend/tests/**

sonar.javascript.lcov.reportPaths=frontend/Note-Taking-App/coverage/lcov.info,backend/coverage/lcov.info